#
# Example: Passwords
#

# Define constant (starts with uppercase letter)
Password = "Daffodil"

# Request first password
puts "Password, please:"
# Note: no need to use to_i, since we want the password as a string.
# However, we do have to use chomp to remove the new line character 
# at the end that is generated by the user typing return.
first_password = gets.chomp

puts "Password again, please:"
second_password = gets.chomp

if (first_password == Password) and (second_password == Password) then
  puts "Both words #{Password} are identical."
else
  puts "The words #{first_password} and #{second_password} are not identical."
end